# This is a basic workflow to help you get started with Actions

name: Update Integrations Marketplace

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: get plugin name
        run: |
          plugin=$(echo ${{ github.repository }} | cut -d'/' -f 2)
          echo "plugin_name=$plugin" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          FILES: |
            manifest.json
            synthetic.xml
            *.png
            *.svg
            steps.json
      - run: echo ${{ env.GIT_DIFF_FILTERED }}

      - uses: actions/checkout@v2
        with:
          repository: xebialabs/integrations-marketplace
          path: integrations-marketplace
          ssh-key: ${{ secrets.key }}

      - run: |
          cp integrations-marketplace/githubactions.sh .
          chmod 777 githubactions.sh
          ./githubactions.sh ${{ env.GIT_DIFF_FILTERED }} ${{ env.plugin_name }} $PWD 'community'
